/**
 * Regenerate lib/generated/pillarFallbacks.ts from the live Sanity
 * `service` + `servicePackage` documents.
 *
 * The three pillar pages (content-technology, content-operations,
 * content-localization) render from Sanity, and only fall back to
 * code-owned constants if Sanity is unreachable. That fallback used to
 * be hand-copied and drifted a long way from what was actually live.
 * This script closes that gap: it reads the current published content
 * and writes it straight into the generated file, so the two can never
 * silently diverge as long as this gets run after a content change.
 *
 * Run whenever pillar-page content changes in the Studio:
 *   npm run sync:pillars
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { createClient } from "@sanity/client";

const PROJECT_ID = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || "0dep7ult";
const DATASET = process.env.NEXT_PUBLIC_SANITY_DATASET || "production";

const CATEGORIES = ["technology", "services", "localization"] as const;
type Category = (typeof CATEGORIES)[number];

type ServiceDoc = {
  title: string;
  heroDescription: string;
  problemIntro: string | null;
  diagnosisItems: string[] | null;
  reframeStatement: string | null;
  ctaText: string | null;
  ctaUrl: string | null;
  seo?: { metaDescription?: string } | null;
};

type PackageDoc = {
  title: string;
  description: string;
  features: string[] | null;
  order: number;
  href?: string | null;
};

function serializePackage(p: PackageDoc) {
  const out: Record<string, unknown> = {
    title: p.title,
    description: p.description,
    features: p.features ?? [],
    order: p.order,
  };
  if (p.href) out.href = p.href;
  return out;
}

function serializeData(category: Category, doc: ServiceDoc, packages: PackageDoc[]) {
  return {
    title: doc.title,
    category,
    heroDescription: doc.heroDescription,
    problemIntro: doc.problemIntro ?? "",
    diagnosisItems: doc.diagnosisItems ?? [],
    reframeStatement: doc.reframeStatement ?? "",
    ctaText: doc.ctaText ?? "",
    ctaUrl: doc.ctaUrl ?? "",
    packages: packages.map(serializePackage),
  };
}

// Re-indents every line after the first so a multi-line JSON.stringify
// block nests correctly inside the surrounding object literal.
function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line, i) => (i === 0 ? line : pad + line))
    .join("\n");
}

async function main(): Promise<void> {
  const token = process.env.SANITY_API_READ_TOKEN;
  if (!token) {
    console.error(
      "Missing SANITY_API_READ_TOKEN. Add it to .env.local (same token lib/sanity.server.ts reads)."
    );
    process.exit(1);
  }

  const client = createClient({
    projectId: PROJECT_ID,
    dataset: DATASET,
    apiVersion: "2026-04-01",
    token,
    useCdn: false, // sanity-economy: allow-no-cdn one-off sync script, not a page request path — wants the current published state, not a cached edge copy
    perspective: "published",
  });

  const entries = await Promise.all(
    CATEGORIES.map(async (category) => {
      const doc = await client.fetch<ServiceDoc | null>(
        `*[_type == "service" && category == $category][0]{
          title, heroDescription, problemIntro, diagnosisItems,
          reframeStatement, ctaText, ctaUrl, seo
        }`,
        { category }
      );

      if (!doc) {
        throw new Error(`No published "service" document found for category "${category}".`);
      }

      const packages = await client.fetch<PackageDoc[]>(
        `*[_type == "servicePackage" && category == $category] | order(order asc){
          title, description, features, order, href
        }`,
        { category }
      );

      return { category, doc, packages };
    })
  );

  const blocks = entries.map(({ category, doc, packages }) => {
    const data = serializeData(category, doc, packages);
    const metaDescription = doc.seo?.metaDescription ?? "";
    return `  ${category}: {
    data: ${indent(JSON.stringify(data, null, 2), 4)} as ServicePageData,
    metaDescription: ${JSON.stringify(metaDescription)},
  },`;
  });

  const banner = `/**
 * AUTO-GENERATED by scripts/sync-pillar-fallbacks.ts — do not hand-edit.
 *
 * Mirrors the live Sanity \`service\` + \`servicePackage\` documents for the
 * three pillar pages, so the code fallback used when Sanity is
 * unreachable never silently drifts from what's actually live there.
 * Whenever pillar-page content changes in the Studio, regenerate this
 * file:
 *
 *   npm run sync:pillars
 */

import type { ServicePageData } from "@/lib/serviceTypes";

export type PillarFallback = {
  data: ServicePageData;
  metaDescription: string;
};

export const PILLAR_FALLBACKS: Record<
  "technology" | "services" | "localization",
  PillarFallback
> = {
${blocks.join("\n")}
};
`;

  const outPath = join(process.cwd(), "lib", "generated", "pillarFallbacks.ts");
  writeFileSync(outPath, banner, "utf8");

  console.log(`Wrote ${outPath}`);
  for (const { category, packages } of entries) {
    console.log(`  ${category}: ${packages.length} package(s)`);
  }
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : String(e));
  process.exit(1);
});
